### ISSUE TITLE
Split the mixin into multiple service specific mixins

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/porter-arm#22]
The current structure of the mixin is really flexible and allows us to quickly add new services by dropping ARM templates into the templates directory. This makes the mixin a little harder to use, however, since we aren't as easily able to report params and outputs in schema form since they change based on the `type` attribute. 

Let's instead pivot and make one mixin per type. This makes things more verbose from a mixin perspective, but it will actually make things more explicit from the Porter manifest perspective (i.e. I'll see that I am actually using cosmos and storage vs just "azure") and we'll be able to better handle the definition of parameters and what not for the JSON schema.

A lot of the functionality is pretty similar across these things, so I think we can have a good bit of common / library code and handle this with building up specific binaries from the cmd/ package and either splitting the templates up into multiple directories so it's really clear or just changing how we call the existing templating stuff

**Comment by carolynvs** [comment]
💯 At the same time, we can move to having an azure mixin feed so that someone can keep up to date on all the azure related mixins easily.

**Comment by jeremyrickard** [comment]
We are going to simplify this mixin to only support ARM templates.
